spring:
  application:
    name: mybatis-test

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?timeZone=UTC
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:/mybatis/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

